name: stactools-esa-worldcover
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal>=3.3
  - geos>=3.3
  - conda-forge::rasterio>=1.3
  - conda-forge::libstdcxx-ng # gdal dependency. Make sure it's from the same channel as gdal
